#include<url_encoder>
#include<iostream>
#include<forward_list>
#include<string.h>
using namespace std;
using namespace wss;

const char * URLEncoder::encode(const char *urlStr)
{
int size;
forward_list<char *> list;
const char *e;
char *_urlStr,*f;
forward_list<char*>::iterator itr=list.before_begin();
if(!urlStr || strlen(urlStr)<=0) return NULL;
e=urlStr;
size=0;
while(*e)
{
if(*e==' ') 
{
f=(char*)malloc(sizeof(char)*2);
strcpy(f,"+");
itr=list.insert_after(itr,f);
size++;
e++;
continue;
}
if(*e==':') 
{
f=(char *)malloc(sizeof(char)*4);
strcpy(f,"%3A");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='/')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%2F");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='?')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%3F");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='#')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%23");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='[')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%5B");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e==']')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%5D");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;

}
if(*e=='@')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%40");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='!')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%21");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='$')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%24");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='&')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%26");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='\'')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%27");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='(')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%28");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e==')')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%29");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='*')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%2A");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='+')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%2B");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e==',')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%2C");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e==';')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%3B");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='=')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%3D");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
if(*e=='%')
{
f=(char*)malloc(sizeof(char)*4);
strcpy(f,"%25");
itr=list.insert_after(itr,f);
size+=3;
e++;
continue;
}
f=(char*)malloc(sizeof(char)*2);
f[0]=*e;
f[1]='\0';
itr=list.insert_after(itr,f);
e++;
size++;
}
_urlStr=(char*)malloc(sizeof(char)*(size+1));
*_urlStr='\0';
for(itr=list.begin();itr!=list.end();++itr) 
{
strcat(_urlStr,*itr);
free(*itr);
}
return (const char*) _urlStr;
}
